# 1. Wstęp

In [1]:
import pandas as pd
import sklearn
import numpy as np
import keras
import seaborn as sns
import matplotlib.pyplot as plt

# 2. Spójrzmy na dane za nim co kolwiek zrobimy

In [2]:
raw_df = pd.read_csv("dataset.csv", index_col="Unnamed: 0")
raw_df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,no,2.2,0,1,no,7,0.6,188,2,...,20,756,2549.0,9,7,19.0,0,0,wifi,medium cost
1,1021,yes,0.5,1,0,yes,53,0.7,136,3,...,905,1988,2631.0,17,3,7.0,1,1,no_wifi,high cost
2,563,yes,0.5,1,2,yes,41,0.9,145,5,...,1263,1716,2603.0,11,2,9.0,1,1,no_wifi,high cost
3,615,yes,2.5,0,0,no,10,0.8,131,6,...,1216,1786,2769.0,16,8,11.0,1,0,no_wifi,high cost
4,1821,yes,1.2,0,13,yes,44,0.6,141,2,...,1208,1212,1411.0,8,2,15.0,1,1,no_wifi,medium cost
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,yes,0.5,1,0,yes,2,0.8,106,6,...,1222,1890,668.0,13,4,19.0,1,1,no_wifi,low cost
1996,1965,yes,2.6,1,0,no,39,0.2,187,4,...,915,1965,2032.0,11,10,16.0,1,1,wifi,high cost
1997,1911,no,0.9,1,1,yes,36,0.7,108,8,...,868,1632,3057.0,9,1,5.0,1,1,no_wifi,very high cost
1998,1512,no,0.9,0,4,yes,46,0.1,145,5,...,336,670,869.0,18,10,19.0,1,1,wifi,low cost
1999,510,yes,2.0,1,5,yes,45,0.9,168,6,...,483,754,3919.0,19,4,2.0,1,1,wifi,very high cost

In [3]:
raw_df.describe()

,battery_power,clock_speed,dual_sim,fc,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen
count,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1913.000000,1935.000000,1935.000000,1873.000000,1935.000000,1935.000000
mean,1240.282687,1.528889,0.509044,4.298708,32.115245,0.504703,140.209819,4.529716,9.932817,646.829457,1255.708527,2120.500784,12.322997,5.757623,10.998398,0.762274,0.501809
std,438.590972,0.820332,0.500047,4.345792,18.161480,0.292660,35.480487,2.285474,6.057774,445.042126,434.465962,1083.400626,4.209676,4.333399,5.457734,0.425801,0.500126
min,501.000000,0.500000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,0.000000,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000
25%,853.500000,0.700000,0.000000,1.000000,16.000000,0.200000,109.000000,3.000000,5.000000,284.500000,880.000000,1205.000000,9.000000,2.000000,6.000000,1.000000,0.000000
50%,1231.000000,1.500000,1.000000,3.000000,32.000000,0.500000,141.000000,4.000000,10.000000,567.000000,1251.000000,2131.000000,12.000000,5.000000,11.000000,1.000000,1.000000
75%,1617.000000,2.250000,1.000000,7.000000,48.000000,0.800000,170.000000,7.000000,15.000000,948.000000,1638.500000,3056.000000,16.000000,9.000000,16.000000,1.000000,1.000000
max,1998.000000,4.000000,1.000000,19.000000,64.000000,2.000000,200.000000,8.000000,20.000000,1960.000000,2298.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000

Super. Popatrzyliśmy na dane w tabelce.


imo można wywalić pewne kolumny:
- Unnamed: 0 - losowy indeksik, niby można użyć jako key przy wczytaniu
- pc i fc są podobne więc wywaliłbym fc, tak dla beki

Zauważamy, że `blue`, `four_g`, `wifi` kodował jakiś humanista i trzeba to przerobić na prawilną binarkę jak w `three_g` `touch_screen`, `dual_sim`

also nie ufałbym wartościom w `m_dep` serio telefon ma 1 mm *grubości* (głębokości)?

In [4]:
raw_df = raw_df.drop(columns=["fc"])

In [ ]:
raw_df

# 3. Preprocessing

In [ ]:
sklearn.set_config(transform_output="pandas")

In [ ]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1935 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  1935 non-null   int64
 1   blue           1915 non-null   object
 2   clock_speed    1935 non-null   float64
 3   dual_sim       1935 non-null   int64
 4   four_g         1935 non-null   object
 5   int_memory     1935 non-null   int64
 6   m_dep          1935 non-null   float64
 7   mobile_wt      1935 non-null   int64
 8   n_cores        1935 non-null   int64
 9   pc             1935 non-null   int64
 10  px_height      1935 non-null   int64
 11  px_width       1935 non-null   int64
 12  ram            1913 non-null   float64
 13  sc_h           1935 non-null   int64
 14  sc_w           1935 non-null   int64
 15  talk_time      1873 non-null   float64
 16  three_g        1935 non-null   int64
 17  touch_screen   1935 non-null   int64
 18  wifi           1935 non-null   object
 19  price_range    1935 non-null   object
dtypes: float64(4), int64(12), object(4)
memory usage: 317.5+ KB

Zauważamy, że puste wartości występują w:
- blue - dane kategoryczne
- ram - dane numeryczne (ciągłe)
- talk_time - dane numeryczne (ciągłe)

In [ ]:
# Filtruje wiersze w których jakaś kolumna jest pusta.
rows_with_missing_values = raw_df[raw_df.isna().any(axis=1)]
rows_with_missing_values

,battery_power,blue,clock_speed,dual_sim,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
14,1866,no,0.5,0,yes,52,0.7,185,1,17,356,563,373.0,14,9,NaN,1,0,wifi,low cost
25,961,yes,1.4,1,yes,57,0.6,114,8,3,291,1434,2782.0,18,9,NaN,1,1,wifi,high cost
45,1514,no,2.9,0,no,27,0.2,118,3,1,186,1810,1152.0,8,3,NaN,0,1,wifi,medium cost
76,1114,no,2.8,0,yes,9,0.4,197,3,15,1040,1071,907.0,10,7,NaN,1,1,no_wifi,low cost
100,1883,yes,0.5,0,yes,10,0.3,146,6,13,836,1739,2600.0,16,8,NaN,1,0,no_wifi,very high cost
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1891,1367,no,2.9,0,no,56,0.8,176,2,6,36,642,NaN,6,2,10.0,0,1,no_wifi,low cost
1899,1837,no,0.5,0,no,36,0.9,162,4,20,786,872,770.0,14,1,NaN,0,0,wifi,low cost
1911,1259,no,1.2,1,no,13,0.5,97,2,0,1210,1989,340.0,17,13,NaN,1,0,wifi,low cost
1949,757,yes,0.9,1,no,64,0.5,157,7,5,114,819,3433.0,6,5,NaN,1,1,no_wifi,high cost
1988,1547,yes,2.9,0,no,57,0.4,114,1,3,347,957,1620.0,9,2,NaN,0,1,wifi,medium cost

In [ ]:
df_numeric = raw_df.select_dtypes(include="number")
df_categ = raw_df.select_dtypes(exclude="number")

from sklearn.impute import SimpleImputer

imputer_numeric = SimpleImputer(strategy='mean')
imputer_numeric.fit(df_numeric)
df_numeric_transformed = imputer_numeric.transform(df_numeric)

In [ ]:
df_numeric = pd.DataFrame(df_numeric_transformed, columns = imputer_numeric.get_feature_names_out())
df_numeric

,battery_power,clock_speed,dual_sim,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen
0,842.0,2.2,0.0,7.0,0.6,188.0,2.0,2.0,20.0,756.0,2549.0,9.0,7.0,19.0,0.0,0.0
1,1021.0,0.5,1.0,53.0,0.7,136.0,3.0,6.0,905.0,1988.0,2631.0,17.0,3.0,7.0,1.0,1.0
2,563.0,0.5,1.0,41.0,0.9,145.0,5.0,6.0,1263.0,1716.0,2603.0,11.0,2.0,9.0,1.0,1.0
3,615.0,2.5,0.0,10.0,0.8,131.0,6.0,9.0,1216.0,1786.0,2769.0,16.0,8.0,11.0,1.0,0.0
4,1821.0,1.2,0.0,44.0,0.6,141.0,2.0,14.0,1208.0,1212.0,1411.0,8.0,2.0,15.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794.0,0.5,1.0,2.0,0.8,106.0,6.0,14.0,1222.0,1890.0,668.0,13.0,4.0,19.0,1.0,1.0
1996,1965.0,2.6,1.0,39.0,0.2,187.0,4.0,3.0,915.0,1965.0,2032.0,11.0,10.0,16.0,1.0,1.0
1997,1911.0,0.9,1.0,36.0,0.7,108.0,8.0,3.0,868.0,1632.0,3057.0,9.0,1.0,5.0,1.0,1.0
1998,1512.0,0.9,0.0,46.0,0.1,145.0,5.0,5.0,336.0,670.0,869.0,18.0,10.0,19.0,1.0,1.0
1999,510.0,2.0,1.0,45.0,0.9,168.0,6.0,16.0,483.0,754.0,3919.0,19.0,4.0,2.0,1.0,1.0

# 4. Analiza

# 5. Model